// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: internal/app/adapter/primary/grpc/proto/grpc.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      []string               `protobuf:"bytes,2,rep,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBatchRequest) Reset() {
	*x = DeleteBatchRequest{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchRequest) ProtoMessage() {}

func (x *DeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteBatchRequest) GetShortUrl() []string {
	if x != nil {
		return x.ShortUrl
	}
	return nil
}

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchRequest_Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRequest) GetItems() []*BatchRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchResponse_Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *BatchResponse) GetItems() []*BatchResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ServiceStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int64                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	UserCount     int64                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatsResponse) Reset() {
	*x = ServiceStatsResponse{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatsResponse) ProtoMessage() {}

func (x *ServiceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatsResponse.ProtoReflect.Descriptor instead.
func (*ServiceStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceStatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *ServiceStatsResponse) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

type UrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlResponse) Reset() {
	*x = UrlResponse{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlResponse) ProtoMessage() {}

func (x *UrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlResponse.ProtoReflect.Descriptor instead.
func (*UrlResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *UrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UrlResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type UserUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UrlResponse         `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUrlResponse) Reset() {
	*x = UserUrlResponse{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlResponse) ProtoMessage() {}

func (x *UserUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlResponse.ProtoReflect.Descriptor instead.
func (*UserUrlResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *UserUrlResponse) GetUrls() []*UrlResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchRequest_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest_Item) Reset() {
	*x = BatchRequest_Item{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest_Item) ProtoMessage() {}

func (x *BatchRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest_Item.ProtoReflect.Descriptor instead.
func (*BatchRequest_Item) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BatchRequest_Item) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequest_Item) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse_Item) Reset() {
	*x = BatchResponse_Item{}
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse_Item) ProtoMessage() {}

func (x *BatchResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse_Item.ProtoReflect.Descriptor instead.
func (*BatchResponse_Item) Descriptor() ([]byte, []int) {
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *BatchResponse_Item) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponse_Item) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_internal_app_adapter_primary_grpc_proto_grpc_proto protoreflect.FileDescriptor

const file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDesc = "" +
	"\n" +
	"2internal/app/adapter/primary/grpc/proto/grpc.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\x12DeleteBatchRequest\x12\x1b\n" +
	"\tshort_url\x18\x02 \x03(\tR\bshortUrl\"\"\n" +
	"\x0eShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\x0fShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x8e\x01\n" +
	"\fBatchRequest\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.api.BatchRequest.ItemR\x05items\x1aP\n" +
	"\x04Item\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\x90\x01\n" +
	"\rBatchResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.api.BatchResponse.ItemR\x05items\x1aP\n" +
	"\x04Item\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"I\n" +
	"\x14ServiceStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x03R\x04urls\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x03R\tuserCount\"M\n" +
	"\vUrlResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"7\n" +
	"\x0fUserUrlResponse\x12$\n" +
	"\x04urls\x18\x01 \x03(\v2\x10.api.UrlResponseR\x04urls2\xe8\x02\n" +
	"\x03Url\x121\n" +
	"\bAddBatch\x12\x11.api.BatchRequest\x1a\x12.api.BatchResponse\x127\n" +
	"\n" +
	"AddShorten\x12\x13.api.ShortenRequest\x1a\x14.api.ShortenResponse\x12>\n" +
	"\vDeleteBatch\x12\x17.api.DeleteBatchRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x0eGetAllByUserID\x12\x16.google.protobuf.Empty\x1a\x14.api.UserUrlResponse\x12=\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x19.api.ServiceStatsResponse\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB7Z5url_shortener/internal/app/adapter/primary/grpc/protob\x06proto3"

var (
	file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescOnce sync.Once
	file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescData []byte
)

func file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescGZIP() []byte {
	file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescOnce.Do(func() {
		file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDesc), len(file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDesc)))
	})
	return file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDescData
}

var file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_app_adapter_primary_grpc_proto_grpc_proto_goTypes = []any{
	(*DeleteBatchRequest)(nil),   // 0: api.DeleteBatchRequest
	(*ShortenRequest)(nil),       // 1: api.ShortenRequest
	(*ShortenResponse)(nil),      // 2: api.ShortenResponse
	(*BatchRequest)(nil),         // 3: api.BatchRequest
	(*BatchResponse)(nil),        // 4: api.BatchResponse
	(*ServiceStatsResponse)(nil), // 5: api.ServiceStatsResponse
	(*UrlResponse)(nil),          // 6: api.UrlResponse
	(*UserUrlResponse)(nil),      // 7: api.UserUrlResponse
	(*BatchRequest_Item)(nil),    // 8: api.BatchRequest.Item
	(*BatchResponse_Item)(nil),   // 9: api.BatchResponse.Item
	(*emptypb.Empty)(nil),        // 10: google.protobuf.Empty
}
var file_internal_app_adapter_primary_grpc_proto_grpc_proto_depIdxs = []int32{
	8,  // 0: api.BatchRequest.items:type_name -> api.BatchRequest.Item
	9,  // 1: api.BatchResponse.items:type_name -> api.BatchResponse.Item
	6,  // 2: api.UserUrlResponse.urls:type_name -> api.UrlResponse
	3,  // 3: api.Url.AddBatch:input_type -> api.BatchRequest
	1,  // 4: api.Url.AddShorten:input_type -> api.ShortenRequest
	0,  // 5: api.Url.DeleteBatch:input_type -> api.DeleteBatchRequest
	10, // 6: api.Url.GetAllByUserID:input_type -> google.protobuf.Empty
	10, // 7: api.Url.GetStats:input_type -> google.protobuf.Empty
	10, // 8: api.Url.Ping:input_type -> google.protobuf.Empty
	4,  // 9: api.Url.AddBatch:output_type -> api.BatchResponse
	2,  // 10: api.Url.AddShorten:output_type -> api.ShortenResponse
	10, // 11: api.Url.DeleteBatch:output_type -> google.protobuf.Empty
	7,  // 12: api.Url.GetAllByUserID:output_type -> api.UserUrlResponse
	5,  // 13: api.Url.GetStats:output_type -> api.ServiceStatsResponse
	10, // 14: api.Url.Ping:output_type -> google.protobuf.Empty
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_app_adapter_primary_grpc_proto_grpc_proto_init() }
func file_internal_app_adapter_primary_grpc_proto_grpc_proto_init() {
	if File_internal_app_adapter_primary_grpc_proto_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDesc), len(file_internal_app_adapter_primary_grpc_proto_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_adapter_primary_grpc_proto_grpc_proto_goTypes,
		DependencyIndexes: file_internal_app_adapter_primary_grpc_proto_grpc_proto_depIdxs,
		MessageInfos:      file_internal_app_adapter_primary_grpc_proto_grpc_proto_msgTypes,
	}.Build()
	File_internal_app_adapter_primary_grpc_proto_grpc_proto = out.File
	file_internal_app_adapter_primary_grpc_proto_grpc_proto_goTypes = nil
	file_internal_app_adapter_primary_grpc_proto_grpc_proto_depIdxs = nil
}
